---
title: '{{TITLE}}'
author: '{{AUTHOR}}'
{{HTML_HEADER}}
---



# Overview



*Welcome to the {{TITLE}} ORGANISATION*


_one_sentence_summary_statement_of_organisation_scope_



{{SEP01}}



# {{TITLE}} : Purpose Statement


{{TITLE}} organisation aims 


* _org_vision_summary_

* _org_mission_summary_

* _org_purpose_summary_


----


* Useful to define Vision, Mission and/or Statement of Purpose 

    + to guide the overall direction of the Organisation : to develop Programmes & Projects
    
    + to help prioritise work


https://www.effectivegovernance.com.au/page/knowledge-centre/news-articles/vision-mission-and-purpose-statements-%E2%80%93-what-is-the-difference

* Vision : The organisation's aspiration
* Mission : What the organisation does
* Purpose : Why the organisation does it


https://en.wikipedia.org/wiki/Strategic_planning

* strategic planning : an organization's process of defining its strategy or direction


https://en.wikipedia.org/wiki/Strategy

* strategy : a general plan to achieve goals under conditions of uncertainty & limited resources


----



## Vision


*The organisations aspiration : to achieve specific objectives*



* _breakdown_of_organisation_aspiration_



----



## Mission


*What the organisations does : to produce protocols datasets knowledge in domain*



* _breakdown_of_organisation_mission_



----



## Statement of Purpose


*Why the organisation does it : deeper reason why organisation work is useful important*



* _statement_of_organisation_purpose_




{{SEP02}}



# Dissemination Plan


> “An updated notion of genius would have to center around one’s mastery of information and its dissemination.”  
Kenneth Goldsmith.  
Uncreative writing : managing language in the digital age, 2011


*Impact can only be made on the world through the dissemination of work.*


>>> 
>>> Notes on ideas to disseminate work from this organisation, including resources and how to disseminate work
>>> 



{{SEP02}}



# projectmanagr documentation


This Organisation is managed using `projectmanagr`


* ProjectManagr : R Package for Project Management using R Markdown Documents

    + See [projectmanagr overview](docs/projectmanagr_overview.Rmd) for usage instructions


* ProjectManagr supports external drives and data servers for external data storage:

    + See [volumes](volumes/volumes.Rmd) for introduction



{{SEP01}}



{{PROGRAMME_HEADER}}


This Organisation defines the following PROGRAMMES that encompass a DOMAINS OF WORK.



{{PROGRAMME_FOOTER}}




