---
title: '{{PREFIX}}~ {{TITLE}}'
author: '{{AUTHOR}}'
{{HTML_HEADER}}
---



{{SUMMARY_HEADER}}


{{PROGLINK}}



*Welcome to the {{TITLE}} Project!*


>>>> succinct description of project scope in one sentence - what does this project hope to achieve?
>>>> Complete the sentence: "This project..."


_one_sentence_summary_statement_of_project_scope__This_Project__


>>>>
>>>> Summarise Project Goals below
>>>> * This Summary will be copied to Project Summary on Programme Index page
>>>>
>>>> * Record Goal Development stages:
>>>>   - Each GOAL is INDEPENDENT:
>>>>   - defines one complete set of objectives : Review, Data Collection & Processing, Analysis, Dissemination
>>>>
>>>> * Record key achievements & progress in this project here
>>>>   - Consider adding a summary GRAPHIC to insert.
>>>>


## __PROJECT_GOAL_TITLE__






## __PROJECT_GOAL_TITLE__






## __PROJECT_GOAL_TITLE__






{{SUMMARY_FOOTER}}



# Project Background Information



>>> Provide background and context to reader
>>> Provide links to other relevant projects
>>> Keep notes on project ideas & research which do not have a note to go into yet..



{{GOAL_SEP}}



{{GOAL_HEADER}} __GOAL_TITLE__



__GOAL_AIMS__


>>>> Each GOAL is INDEPENDENT
>>>>  All the work to achieve one key aim : REVIEW, DEVELOPMENT, ANALYSIS, DISSEMINATION
>>>> Breakdown work into GOALS : INDEPENDENT DOMAINS of Project Objectives
>>>>    Consider DPAD Workflow : Develop > Process > Analyse > Disseminate
>>>>    GOALS capture DOMAINS of work 
>>>>    DELIVERABLES Capture a well-defined achievement in a domain 
>>>>    TASKS capture individual steps/iterations on a deliverable
>>>>
>>>>    REMEMBER : Each project note can be assigned MORE THAN ONE PROJECT GOAL > DELIVERABLE > TASK (GDT)
>>>>      This mechanism is the heart of how projectmaangr EFFICIENTLY MAPS WORK ACROSS MULTIPLE GOALS
>>>>      relevant work in each note can be effectively CROSS-REFERENCED to all relevant GDTs
>>>>



{{DELIVERABLE_SEP}}



{{DELIVERABLE_HEADER}} __DELIVERABLE_TITLE__



__DELIVERABLE_AIMS__



{{TASK_SEP}}



{{TASK_HEADER}} __TASK_TITLE__



__TASK_OVERVIEW__





{{PROJECT_TASK_LOG}}



{{TASK_FOOTER}}



{{TASK_HEADER}} __TASK_TITLE__



__TASK_OVERVIEW__





{{PROJECT_TASK_LOG}}



{{DELIVERABLE_SEP}}



{{DELIVERABLE_HEADER}} __DELIVERABLE_TITLE__



__DELIVERABLE_AIMS__



{{TASK_SEP}}



{{TASK_HEADER}} __TASK_TITLE__



__TASK_OVERVIEW__





{{PROJECT_TASK_LOG}}



{{TASK_FOOTER}}



{{TASK_HEADER}} __TASK_TITLE__



__TASK_OVERVIEW__





{{PROJECT_TASK_LOG}}



{{GOAL_SEP}}



{{GOAL_HEADER}} __GOAL_TITLE__



__GOAL_AIMS__



{{DELIVERABLE_SEP}}



{{DELIVERABLE_HEADER}} __DELIVERABLE_TITLE__



__DELIVERABLE_AIMS__



{{TASK_SEP}}



{{TASK_HEADER}} __TASK_TITLE__



__TASK_OVERVIEW__





{{PROJECT_TASK_LOG}}



{{TASK_FOOTER}}



{{TASK_HEADER}} __TASK_TITLE__



__TASK_OVERVIEW__





{{PROJECT_TASK_LOG}}



{{DELIVERABLE_SEP}}



{{DELIVERABLE_HEADER}} __DELIVERABLE_TITLE__



__DELIVERABLE_AIMS__



{{TASK_SEP}}



{{TASK_HEADER}} __TASK_TITLE__



__TASK_OVERVIEW__





{{PROJECT_TASK_LOG}}



{{TASK_FOOTER}}



{{TASK_HEADER}} __TASK_TITLE__



__TASK_OVERVIEW__





{{PROJECT_TASK_LOG}}



{{GOAL_SEP}}



{{GOAL_HEADER}} __GOAL_TITLE__



__GOAL_AIMS__



{{DELIVERABLE_SEP}}



{{DELIVERABLE_HEADER}} __DELIVERABLE_TITLE__



__DELIVERABLE_AIMS__



{{TASK_SEP}}



{{TASK_HEADER}} __TASK_TITLE__



__TASK_OVERVIEW__





{{PROJECT_TASK_LOG}}



{{TASK_FOOTER}}



{{TASK_HEADER}} __TASK_TITLE__



__TASK_OVERVIEW__





{{PROJECT_TASK_LOG}}



{{DELIVERABLE_SEP}}



{{DELIVERABLE_HEADER}} __DELIVERABLE_TITLE__



__DELIVERABLE_AIMS__



{{TASK_SEP}}



{{TASK_HEADER}} __TASK_TITLE__



__TASK_OVERVIEW__





{{PROJECT_TASK_LOG}}



{{TASK_FOOTER}}



{{TASK_HEADER}} __TASK_TITLE__



__TASK_OVERVIEW__





{{PROJECT_TASK_LOG}}



{{GOAL_SEP}}






