|
  SiteDir: site
  FileType: 'Rmd'
  VolumesDir: volumes
  VolumesFile: volumes.Rmd
  DocsDir: docs
  ConfigStatusYamlFile: status.yml
  OrgIndexFileNamePrefix: index_
  OrgProgrammeHeader: '# PROGRAMMES'
  OrgProgrammeFooter: 'template:SEP01.txt'
  OrgProgrammeSummarySep: 'template:SEP02.txt'
  ProgrammeProjectsDir: PROJECTS
  ProgIndexFileNamePrefix: index_
  ProgSummaryHeader: '# PROGRAMME OVERVIEW'
  ProgSummaryTitle: '# '
  ProgSummaryFooter: 'template:SEP01.txt'
  ProgProjectsHeader: '# PROJECTS'
  ProgProjectsFooter: 'template:SEP01.txt'
  ProgProjectSummarySep: 'template:SEP02.txt'
  ProjectPrefixSep: '~_'
  ProjectIdentifierSep: '_'
  ProjectIndexSep: '~'
  ProjectSummaryHeader: '# PROJECT SUMMARY'
  ProjectSummaryTitle: '# '
  ProjectSummaryFooter: 'template:SEP01.txt'
  ProjectGoalHeader: '# GOAL'
  ProjectGoalTitle: 'GOAL'
  ProjectGoalDivider: ':'
  ProjectGoalSep: 'template:SEP01.txt'
  ProjectDeliverableHeader: '## DELIVERABLE'
  ProjectDeliverableTitle: 'DELIVERABLE'
  ProjectDeliverableDivider: ':'
  ProjectDeliverableSep: 'template:SEP02.txt'
  ProjectTaskHeader: '### TASK'
  ProjectTaskTitle: 'TASK'
  ProjectTaskDivider: ':'
  ProjectTaskSep: 'template:SEP03.txt'
  ProjectTaskFooter: 'template:SEP04.txt'
  ProjectLinkFormat: ''
  ProjectTaskOverviewHeader: '#### OVERVIEW'
  ProjectTaskLogHeader: '#### LOG'
  ProjectTaskLogSep: '------------'
  NoteObjectivesSummarySectionHeader: '**SUMMARY**'
  NoteObjectivesTodoSectionHeader: '**TODO**'
  NoteObjectivesHeader: '# OBJECTIVES'
  NoteObjectivesSep: 'template:SEP02.txt'
  NoteObjectivesFooter: 'template:SEP01.txt'
  NoteStorageHeader: '# DATA STORAGE'
  NoteStorageFooter: 'template:SEP02.txt'
  NoteLinkFormat: '**'
  GroupNotePrefixSep: '-'
  HeaderNotePrefix: '00'
  HeaderNoteContentsHeader: '# CONTENTS'
  HeaderNoteContentsFooter: 'template:SEP03.txt'
  HeaderLinkFormat: '**'
  SubNotePrefixSep: '-'
  SubNoteContentsHeader: '# GROUP CONTENTS'
  SubNoteContentsFooter: 'template:SEP03.txt'
  SubNoteLinkFormat: '*'
  NoteSummaryTitle: '## '
  NoteGoalLinkLine: '* [GOAL'
  NoteDeliverableLinkLine: '    + [DELIVERABLE'
  NoteTaskLinkLine: '        - [TASK'
  ContentHeader: '# CONTENT : '
  ContentSep: 'template:CONTENT_SEP.txt'
  ContentDescriptionField: 'CONTENT_DESCRIPTION:'
  ContentInsertionTitle: '# '
  ContentInsertionSep: 'template:SEP01.txt'
  ContentLinkFormat: '**'
  ContentSummaryHeader: '# SUMMARY'
  ContentSummaryFooter: 'template:SEP01.txt'
  ContentGraphicalAbstractHeader: '# Graphical Abstract'
  ContentGraphicalAbstractSvg: 'graphical-abstract.svg'
  ContentGraphicalAbstractFooter: 'template:SEP02.txt'
  ContentBackgroundHeader: '# Background'
  ContentBackgroundFooter: 'template:SEP02.txt'
  ContentMaterialsHeader: '# EQUIPMENT & MATERIAL'
  ContentMaterialsFooter: 'template:SEP01.txt'
  ContentEquipmentSvg: '00-equipment-material.svg'
  ContentProcedureTemplateSvg: '01-procedure-schematic.svg'
  ContentResultsLogHeader: '# RESULTS LOG'
  ContentResultsLogFooter: 'template:SEP01.txt'
  ContentTroubleshootingHeader: '# TROUBLESHOOTING GUIDE'
  ContentTroubleshootingFooter: 'template:SEP01.txt'
  ContentSopHeader: 'template:SEP03.txt'
  ContentLogHeader: 'template:SEP02.txt'
  ContentLogSep: 'template:SEP03.txt'
  ContentFooter: 'template:SEP01.txt'
  TodoItemHeaderTemplate: '### [] TODO_DESCRIPTION'
  TodoItemHeaderComplete: '### [x]'
  TodoItemHeader: '### ['
  TodoCollectionDir: todo
  TodoProgrammeSep: 'template:SEP02.txt'
  DateTimeZone: 'UTC'
  DateSplit: '-'
  DateTimeSplit: ':'
  RunUpdateOnStartup: yes
  RunCompileWithUpdate: yes
  FileTypeSuffix: 'Rmd'
  WeeklyJournalDir: 'weekly-journal'
  GadgetWidth: 1200
  GadgetHeight: 1200
  rstudioInternalStateDir: ~/.local/share/rstudio
