|
  SiteDir: site
  FileType: Rmd
  VolumesDir: volumes
  VolumesFile: volumes.Rmd
  ConfigStatusYamlFile: status.yml
  OrgIndexFileNamePrefix: _index_
  OrgProgrammeHeader: '# PROGRAMMES'
  OrgProgrammeFooter: ::template::SEP01.txt
  OrgProgrammeSummarySep: ::template::SEP02.txt
  ProgIndexFileNamePrefix: _index_
  ProgSummaryHeader: '# PROGRAMME OVERVIEW'
  ProgSummaryTitle: '# '
  ProgSummaryFooter: ::template::SEP01.txt
  ProgStrategicObjectivesHeader: '# Strategic Objectives'
  ProgStrategicObjectivesFooter: ::template::SEP01.txt
  ProgProjectsHeader: '# SUB-SECTIONS AND PROJECTS'
  ProgProjectsFooter: ::template::SEP01.txt
  ProgProjectSummarySep: ::template::SEP02.txt
  SectionIndexFileNamePrefix: _index_
  SectionSummaryHeader: '# PROGRAMME SECTION OVERVIEW'
  SectionSummaryTitle: '# '
  SectionSummaryFooter: ::template::SEP01.txt
  SectionProjectsHeader: '# SUB-SECTIONS AND PROJECTS'
  SectionProjectsFooter: ::template::SEP01.txt
  SectionProjectSummarySep: ::template::SEP02.txt
  ProjectPrefixSep: ~_
  ProjectIdentifierSep: _
  ProjectIndexSep: '~'
  ProjectSummaryHeader: '# PROJECT SUMMARY'
  ProjectSummaryTitle: '# '
  ProjectSummaryFooter: ::template::SEP01.txt
  ProjectGoalHeader: '# GOAL:'
  ProjectGoalTitle: GOAL
  ProjectGoalDivider: ':'
  ProjectGoalSep: ::template::SEP01.txt
  ProjectDeliverableHeader: '## DELIVERABLE:'
  ProjectDeliverableTitle: DELIVERABLE
  ProjectDeliverableDivider: ':'
  ProjectDeliverableSep: ::template::SEP02.txt
  ProjectTaskHeader: '### TASK:'
  ProjectTaskTitle: TASK
  ProjectTaskDivider: ':'
  ProjectTaskSep: ::template::SEP03.txt
  ProjectTaskFooter: ::template::SEP04.txt
  ProjectLinkFormat: ''
  ProjectTaskLogHeader: '#### log'
  ProjectTaskLogSep: '------------'
  NoteObjectivesTodoSectionHeader: ::template::TODO_HEADER.txt
  NoteObjectivesHeader: '# OBJECTIVES'
  NoteObjectivesSep: ::template::SEP02.txt
  NoteObjectivesFooter: ::template::SEP01.txt
  NoteStorageHeader: '# DATA STORAGE'
  NoteStorageFooter: ::template::SEP02.txt
  NoteLinkFormat: '**'
  GroupNotePrefixSep: '-'
  HeaderNotePrefix: '00'
  HeaderNoteContentsHeader: '# CONTENTS'
  HeaderNoteContentsFooter: ::template::SEP03.txt
  HeaderLinkFormat: '**'
  SubNotePrefixSep: '-'
  SubNoteContentsHeader: '# GROUP CONTENTS'
  SubNoteContentsFooter: ::template::SEP03.txt
  SubNoteLinkFormat: '*'
  NoteSummaryTitle: '## '
  NoteGoalLinkLine: '* [GOAL'
  NoteDeliverableLinkLine: '    + [DELIVERABLE'
  NoteTaskLinkLine: '        - [TASK'
  ContentTitleField: 'CONTENT_TITLE:'
  ContentDescriptionField: 'CONTENT_DESCRIPTION:'
  ContentSourceField: 'CONTENT_SOURCE:'
  ContentSep: ::template::CONTENT_SEP.txt
  ContentInsertionTitle: '# '
  ContentInsertionSep: ::template::SEP01.txt
  ContentLinkFormat: '**'
  ContentSummaryHeader: '# SUMMARY'
  ContentSummaryFooter: ::template::SEP01.txt
  ContentGraphicalAbstractHeader: '# Graphical Abstract'
  ContentGraphicalAbstractSvg: graphical-abstract.svg
  ContentGraphicalAbstractFooter: ::template::SEP02.txt
  ContentBackgroundHeader: '# Background'
  ContentBackgroundFooter: ::template::SEP02.txt
  ContentMaterialsHeader: '# EQUIPMENT & MATERIAL'
  ContentMaterialsFooter: ::template::SEP01.txt
  ContentEquipmentSvg: 00-equipment-material.svg
  ContentProcedureTemplateSvg: 01-procedure-schematic.svg
  ContentResultsLogHeader: '# RESULTS LOG'
  ContentResultsLogFooter: ::template::SEP01.txt
  ContentTroubleshootingHeader: '# TROUBLESHOOTING GUIDE'
  ContentTroubleshootingFooter: ::template::SEP01.txt
  ContentSopHeader: ::template::SEP03.txt
  ContentLogHeader: ::template::SEP02.txt
  ContentLogSep: ::template::SEP03.txt
  ContentFooter: ::template::SEP01.txt
  TodoHeader: '### '
  TodoHeaderTemplate: '### TODO_HEADER'
  TodoItem: '#### ['
  TodoItemTemplate: '#### [] _todo_item_description_'
  TodoItemComplete: '#### [x]'
  TodoCollectionSep: ::template::SEP01.txt
  TodoProgrammeSep: ::template::SEP02.txt
  TodoProjectNoteSep: ::template::SEP03.txt
  TodoTaskHeader: '## '
  TodoGDTSep: ::template::SEP04.txt
  DateTimeZone: UTC
  DateSplit: '-'
  DateTimeSplit: ':'
  DatatableExportHeader: '# EXPORT : '
  RunUpdateOnStartup: yes
  RunCompileWithUpdate: yes
  FileTypeSuffix: Rmd
  JournalDir: journal
  JournalMetadataFooter: ::template::SEP01.txt
  JournalEventsHeader: "# TODAY'S EVENTS"
  JournalEventsFooter: ::template::SEP01.txt
  JournalEventsInsertion: "__insert_events_scheduled_for_today__"
  JournalTodosHeader: "# TODAY'S AGENDA"
  JournalTodosFooter: ::template::SEP01.txt
  JournalTodosInsertion: "__insert_TODO_items__"
  GadgetWidth: 1200
  GadgetHeight: 1200
  rstudioInternalStateDir: ~/.local/share/rstudio
